version: '3'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8080:3000"
    restart: always

  frontend:
    container_name: front-end
    depends_on:
      - api
    build:
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "3000:80"
    restart: always

